cronJob:
  schedule: "0 6 * * *"  # Run every day at 6 AM (adjust as needed)
  image:
    repository: ghcr.io/angelscloud/prometheus-optimizer
    tag: latest
    pullPolicy: Always

serviceAccount:
  name: prometheus-optimizer-service-account

configMap:
  data:
    grafana:
      enabled: true
      api_token: ""
      address: "http://kube-prometheus-grafana.kube-prometheus.svc:80"

    prometheus_analysis:
      enabled: true
      address: "http://mimir-test-query-frontend.mimir-test.svc:8080"

    fetch_rules:
      enabled: true
      prometheus_discovery:
        namespace: "kube-prometheus"
        labels:
          app.kubernetes.io/name: prometheus
          app.kubernetes.io/instance: kube-prometheus-kube-prome-prometheus

    slack:
      token: "<PUT-YOUR-SLACK-BOT-TOKEN-HERE>"
      channel: "#metrics-optimizer"

    mark_as_used_metric: "^maas.*"
